────────────────────────────────────────────────────────────────────────────────────────────────────── lint ──────────────────────────────────────────────────────────────────────────────────────────────────────
cmd [1] | flake8
./tests/conftest.py:288:65: B023 Function definition does not bind loop variable 'ps'.
./tests/debugging/exploration/_profiler.py:65:13: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
./tests/contrib/aiomysql/test_aiomysql.py:5:1: I001 isort found an import in the wrong position
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:82:121: E501 line too long (125 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:84:121: E501 line too long (133 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:85:121: E501 line too long (125 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:86:121: E501 line too long (141 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:87:121: E501 line too long (133 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:88:121: E501 line too long (125 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:89:121: E501 line too long (127 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:90:121: E501 line too long (131 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:91:121: E501 line too long (125 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:92:121: E501 line too long (125 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:94:121: E501 line too long (123 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:95:121: E501 line too long (123 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:97:121: E501 line too long (131 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:98:121: E501 line too long (149 > 120 characters)
./tests/contrib/pytest_benchmark/test_pytest_benchmark.py:99:121: E501 line too long (129 > 120 characters)
./tests/contrib/httplib/test_httplib.py:139:1: W293 blank line contains whitespace
./tests/contrib/tornado/utils.py:5:1: I001 isort found an import in the wrong position
./tests/contrib/tornado/utils.py:6:1: I001 isort found an import in the wrong position
./tests/contrib/pylons/test_pylons.py:10:1: I001 isort found an import in the wrong position
./tests/contrib/grpc_aio/test_grpc_aio.py:105:13: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./tests/contrib/django/conftest.py:6:1: F811 redefinition of unused 'os' from line 1
./tests/contrib/django/conftest.py:6:1: I001 isort found an import in the wrong position
./tests/contrib/django/conftest.py:56:1: E302 expected 2 blank lines, found 1
./tests/contrib/django/conftest.py:60:1: E305 expected 2 blank lines after class or function definition, found 1
./tests/contrib/django/conftest.py:68:30: W292 no newline at end of file
./tests/contrib/rq/test_rq.py:18:1: I001 isort found an import in the wrong position
./tests/contrib/rq/test_rq.py:19:1: I005 isort found an unexpected missing import
./tests/contrib/rq/test_rq.py:19:1: I005 isort found an unexpected missing import
./tests/appsec/test_remoteconfiguration_e2e.py:272:5: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./tests/appsec/test_remoteconfiguration_e2e.py:292:5: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./tests/appsec/iast/iast_utils.py:13:5: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./tests/appsec/iast/fixtures/aspects/str_methods.py:795:41: W291 trailing whitespace
./tests/profiling/simple_program.py:16:5: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./tests/profiling/collector/test_stack.py:305:13: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./tests/profiling/collector/test_threading.py:350:9: B011 Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError().
./benchmarks/bm/_scenario.py:83:13: B012 return/continue/break inside finally blocks cause exceptions to be silenced. Exceptions should be silenced in except blocks. Control statements can be moved outside the finally block.
./ddtrace/bootstrap/sitecustomize.py:63:9: B028 No explicit stacklevel keyword argument found. The warn method from the warnings module uses a stacklevel of 1 by default. This will only show a stack trace for the line on which the warn method is called. It is therefore recommended to use a stacklevel of 2 or greater to provide more information to the user.
./ddtrace/ext/ci.py:11:1: I001 isort found an import in the wrong position
./ddtrace/ext/ci.py:243:22: B005 Using .strip() with multi-character strings is misleading the reader. It looks like stripping a substring. Move your character set to a constant if this is deliberate. Use .replace(), .removeprefix(), .removesuffix(), or regular expressions to remove string fragments.
./ddtrace/internal/injection.py:49:14: F821 undefined name 'i'
./ddtrace/internal/injection.py:49:16: F821 undefined name 'i'
./ddtrace/internal/injection.py:58:14: F821 undefined name 'i'
./ddtrace/internal/injection.py:58:16: F821 undefined name 'i'
./ddtrace/internal/injection.py:69:14: F821 undefined name 'i'
./ddtrace/internal/injection.py:69:16: F821 undefined name 'i'
./ddtrace/internal/utils/http.py:349:9: B014 Redundant exception types in `except (OSError, IOError) as e:`.  Write `except OSError as e:`, which catches exactly the same exceptions.
./ddtrace/internal/datadog/profiling/ddup.py:5:1: I001 isort found an import in the wrong position
./ddtrace/internal/datadog/profiling/ddup.py:6:1: I003 isort expected 1 blank line in imports, found 0
./ddtrace/contrib/asgi/utils.py:53:8: B004 Using `hasattr(x, '__call__')` to test if `x` is callable is unreliable. If `x` implements custom `__getattr__` or its `__call__` is itself not callable, you might get misleading results. Use `callable(x)` for consistent results.
./ddtrace/contrib/httplib/patch.py:14:1: I001 isort found an import in the wrong position
./ddtrace/contrib/psycopg/patch.py:193:89: B026 Star-arg unpacking after a keyword argument is strongly discouraged, because it only works when the keyword parameter is declared after all parameters supplied by the unpacked sequence, and this change of ordering can surprise and mislead readers.
./ddtrace/contrib/django/patch.py:535:25: B012 return/continue/break inside finally blocks cause exceptions to be silenced. Exceptions should be silenced in except blocks. Control statements can be moved outside the finally block.
./ddtrace/contrib/openai/patch.py:394:21: B012 return/continue/break inside finally blocks cause exceptions to be silenced. Exceptions should be silenced in except blocks. Control statements can be moved outside the finally block.
./ddtrace/contrib/openai/patch.py:420:21: B012 return/continue/break inside finally blocks cause exceptions to be silenced. Exceptions should be silenced in except blocks. Control statements can be moved outside the finally block.
