[[{"name" "rq.queue.enqueue_job"
   "service" "rq"
   "resource" "tests.contrib.rq.jobs.job_fail"
   "type" "worker"
   "error" 0
   "span_id" 0
   "trace_id" 0
   "parent_id" nil
   "start" 1630333148970118000
   "duration" 4247600
   "meta" {"runtime-id" "db58ccbfef044eeab2b2670b8b124068"
           "queue.name" "q"
           "job.id" "be34a76b-aa9e-455e-9b33-d98da5c66cd7"
           "job.func_name" "tests.contrib.rq.jobs.job_fail"}
   "metrics" {"_dd.agent_psr" 1.0
              "_sampling_priority_v1" 1
              "system.pid" 462
              "_dd.tracer_kr" 1.0}}
      {"name" "rq.worker.perform_job"
       "service" "rq-worker"
       "resource" "tests.contrib.rq.jobs.job_fail"
       "type" "worker"
       "error" 1
       "span_id" 1
       "trace_id" 0
       "parent_id" 0
       "start" 1630333148986879600
       "duration" 18437200
       "meta" {"runtime-id" "db58ccbfef044eeab2b2670b8b124068"
               "job.id" "be34a76b-aa9e-455e-9b33-d98da5c66cd7"
               "job.status" "failed"
               "job.origin" "q"}
       "metrics" {"_sampling_priority_v1" 1
                  "system.pid" 462
                  "_dd.tracer_kr" 1.0}}
          {"name" "rq.job.perform"
           "service" "rq-worker"
           "resource" "tests.contrib.rq.jobs.job_fail"
           "error" 1
           "span_id" 2
           "trace_id" 0
           "parent_id" 1
           "start" 1630333148988998200
           "duration" 2697400
           "meta" {"job.id" "be34a76b-aa9e-455e-9b33-d98da5c66cd7"
                   "error.msg" "error"
                   "error.type" "tests.contrib.rq.jobs.MyException"
                   "error.stack" "Traceback (most recent call last):\n  File \"/root/project/ddtrace/contrib/rq/__init__.py\", line 173, in traced_job_perform\n    return func(*args, **kwargs)\n  File \"/root/project/.riot/venv_py387_rq~100_redis30/lib/python3.8/site-packages/rq/job.py\", line 588, in perform\n    self._result = self._execute()\n  File \"/root/project/.riot/venv_py387_rq~100_redis30/lib/python3.8/site-packages/rq/job.py\", line 594, in _execute\n    return self.func(*self.args, **self.kwargs)\n  File \"/root/project/tests/contrib/rq/jobs.py\", line 10, in job_fail\n    raise MyException(\"error\")\ntests.contrib.rq.jobs.MyException: error\n"}}]]
