[[
  {
    "name": "mariadb.query",
    "service": "mariadb",
    "resource": "SELEC 1",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 0,
    "type": "sql",
    "error": 1,
    "meta": {
      "_dd.base_service": "",
      "_dd.p.dm": "-0",
      "component": "mariadb",
      "db.name": "test",
      "db.system": "mariadb",
      "db.user": "test",
      "error.message": "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELEC 1' at line 1",
      "error.stack": "Traceback (most recent call last):\n  File \"/root/project/ddtrace/contrib/dbapi/__init__.py\", line 124, in _trace_method\n    return method(*args, **kwargs)\nmariadb.ProgrammingError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELEC 1' at line 1\n",
      "error.type": "mariadb.ProgrammingError",
      "language": "python",
      "out.host": "127.0.0.1",
      "runtime-id": "82fb0609ae3943fd9aed73ca9abbca8f",
      "span.kind": "client"
    },
    "metrics": {
      "_dd.measured": 1,
      "_dd.top_level": 1,
      "_dd.tracer_kr": 1.0,
      "_sampling_priority_v1": 1,
      "db.row_count": -1,
      "network.destination.port": 3306,
      "process_id": 19547
    },
    "duration": 1391250,
    "start": 1692647267106458128
  }]]
