[[{"name" "cherrypy.request"
   "service" "test.cherrypy.service"
   "resource" "GET /fatal"
   "type" "web"
   "error" 1
   "span_id" 0
   "trace_id" 0
   "parent_id" nil
   "start" 1612565277591986000
   "duration" 1596000
   "meta" {"runtime-id" "9ec4e861797b401289c15e82e1a86a76"
           "error.type" "<class 'ZeroDivisionError'>"
           "error.msg" "division by zero"
           "error.stack" "Traceback (most recent call last):\n  File \"/Users/kyle.verhoog/dev/dd-trace-py/.riot/.venv_py377/lib/python3.7/site-packages/cherrypy/_cprequest.py\", line 634, in respond\n    self._do_respond(path_info)\n  File \"/Users/kyle.verhoog/dev/dd-trace-py/.riot/.venv_py377/lib/python3.7/site-packages/cherrypy/_cprequest.py\", line 693, in _do_respond\n    response.body = self.handler()\n  File \"/Users/kyle.verhoog/dev/dd-trace-py/.riot/.venv_py377/lib/python3.7/site-packages/cherrypy/lib/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"/Users/kyle.verhoog/dev/dd-trace-py/.riot/.venv_py377/lib/python3.7/site-packages/cherrypy/_cpdispatch.py\", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/Users/kyle.verhoog/dev/dd-trace-py/tests/contrib/cherrypy/web.py\", line 64, in fatal\n    1 / 0\nZeroDivisionError: division by zero\n"
           "http.method" "GET"
           "http.url" "http://127.0.0.1:54583/fatal"
           "http.status_code" "500"
           "http.request.headers.host" "127.0.0.1:54583"}
   "metrics" {"_dd.agent_psr" 1.0
              "_sampling_priority_v1" 1
              "_dd.tracer_kr" 1.0
              "system.pid" 12166}}]]
